### ISSUE TITLE
Confusion about prediction and true labels?

### ISSUE THREAD

**Issue by ersinyar** [kamalkraj/Named-Entity-Recognition-with-Bidirectional-LSTM-CNNs#2] opened 2018-02-20 08:14 UTC
Thank you for sharing your code. I have question related to prediction and true labels. In validation part, I have printed label_pred and label_correct in compute_f1 function. What I expected is that we should have a list of list of strings for labels. First list corresponds to sentences and the second list corresponds to a list of labels for a specific sentence. But, I observed the following situation. This attached image corresponds to label_correct in compute_f1 function. As one can see, sentences contain only one prediction. I wonder what I am missing. I expect to have a list of numbers whose length is equal to the number of entities in a sentence. Can you help me here? Thanks.
![screen shot 2018-02-20 at 11 11 10](https://user-images.githubusercontent.com/19571570/36413306-d64b5b4a-162e-11e8-9007-9e6026ce61ae.png)

**Comment by kamalkraj** [comment] 2018-02-21 11:52
It is issue caused by while reading the validation file. Fixed now 
Let me know still problem exist

**Closed as completed** 2018-02-23 13:35 UTC
